on:
  workflow_dispatch: 

jobs:
  test-windows:
    runs-on: windows-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
      - run: go test ./...

  test-linux:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
      - run: go test ./...